### ISSUE TITLE
NoSuchMethodError: getResourceLock(int)

### ISSUE THREAD

**Issue by marcel-becker** [IntershopCommunicationsAG/jaxb-gradle-plugin#50]
Hi, 
Using:
   id 'com.intershop.gradle.jaxb' version '5.1.0'

I upgraded Gradle from version 7.4.2 to version 7.5 and I started getting this error:

FAILURE: Build failed with an exception.

* What went wrong:
'org.gradle.internal.resources.ResourceLock org.gradle.internal.resources.SharedResource.getResourceLock(int)'

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: 'org.gradle.internal.resources.ResourceLock org.gradle.internal.resources.SharedResource.getResourceLock(int)'
        at com.intershop.gradle.jaxb.task.SchemaToJavaTask.getSharedResources(SchemaToJavaTask.kt:382)
        at com.intershop.gradle.jaxb.task.SchemaToJavaTask_Decorated.getSharedResources(Unknown Source)
        at org.gradle.execution.plan.LocalTaskNode.getResourcesToLock(LocalTaskNode.java:90)
        at org.gradle.execution.plan.DefaultExecutionPlan.tryLockSharedResourceFor(DefaultExecutionPlan.java:785)
        at org.gradle.execution.plan.DefaultExecutionPlan.tryAcquireLocksForNode(DefaultExecutionPlan.java:739)
        at org.gradle.execution.plan.DefaultExecutionPlan.attemptToStart(DefaultExecutionPlan.java:710)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:682)
        at org.gradle.execution.plan.DefaultPlanExecutor$MergedQueues.selectNext(DefaultPlanExecutor.java:200)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$getNextItem$1(DefaultPlanExecutor.java:392)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:110)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.getNextItem(DefaultPlanExecutor.java:367)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:332)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)

**Comment by marcel-becker** [comment]
Hi @m-raab, 
any updates on this? 
Are you still maintaining this plugin? 
It seems the fix to this problem is to replace the call in  
com.intershop.gradle.jaxb.task.SchemaToJavaTask.getSharedResources(SchemaToJavaTask.kt:382)
from: 
org.gradle.internal.resources.SharedResource.getResourceLock(int)'
to
org.gradle.internal.resources.SharedResource.getResourceLock()'

but this will be a breaking change since the new version of  the plugin will not work with gradle < 7.5. 

Marcel

**Comment by schlagi123** [comment]
Hi @marcel-becker 

i had the same problem with the 5.1.0 version. With an update to the version 5.2.1 this problem is fixed. This issue can be closed.

**Comment by povisenko** [comment]
Have the same issue
Gradle 7.6

**Comment by povisenko** [comment]
@m-raab pls update version in Readme to 5.2.1
