### ISSUE TITLE
Gradle 8.0.1 -- No such method error: org.gradle.internal.resources.SharedResource

### ISSUE THREAD

**Issue by marcel-becker** [IntershopCommunicationsAG/jaxb-gradle-plugin#53]
After upgrading to Gradle 8, my build fails with this message: 

FAILURE: Build failed with an exception.

* What went wrong:
'org.gradle.internal.resources.SharedResource org.gradle.api.services.internal.BuildServiceRegistryInternal.forService(org.gradle.api.provider.Provider)'

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: 'org.gradle.internal.resources.SharedResource org.gradle.api.services.internal.BuildServiceRegistryInternal.forService(org.gradle.api.provider.Provider)'
        at com.intershop.gradle.jaxb.task.SchemaToJavaTask.getSharedResources(SchemaToJavaTask.kt:376)
        at com.intershop.gradle.jaxb.task.SchemaToJavaTask_Decorated.getSharedResources(Unknown Source)
        at org.gradle.execution.plan.LocalTaskNode.getResourcesToLock(LocalTaskNode.java:92)
        at org.gradle.execution.plan.DefaultFinalizedExecutionPlan.tryLockSharedResourceFor(DefaultFinalizedExecutionPlan.java:388)
        at org.gradle.execution.plan.DefaultFinalizedExecutionPlan.tryAcquireLocksForNode(DefaultFinalizedExecutionPlan.java:341)
        at org.gradle.execution.plan.DefaultFinalizedExecutionPlan.attemptToStart(DefaultFinalizedExecutionPlan.java:312)
        at org.gradle.execution.plan.DefaultFinalizedExecutionPlan.selectNext(DefaultFinalizedExecutionPlan.java:279)
        at org.gradle.execution.plan.DefaultPlanExecutor$MergedQueues.selectNext(DefaultPlanExecutor.java:250)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$getNextItem$1(DefaultPlanExecutor.java:433)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:105)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.getNextItem(DefaultPlanExecutor.java:403)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:374)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

**Comment by sreich** [comment]
any sort of update on this guy? it's a new issue, and gradle 8.0 just came out. Still, i am considering using this plugin but it tying me to < gradle 8.0 would be tech debt i don't really want to take on if it wouldn't get addressed

**Comment by povisenko** [comment]
+1 here

**Comment by u2032** [comment]
Hello people 👋🏼 

I had the same problem and made a pull request to try to upgrade the code to support the breaking changes introduced in Gradle 8

The existing tests are 🟢 so I think it works.
But feel free to review, makes changes and merge if needed 

Having soon a new compatible published version coud be great :) 
Thanks

**Comment by marcel-becker** [comment]
Any updates on this issue and the associated merge request?

**Comment by marcel-becker** [comment]
I think this repo is not maintained anymore. Time to switch to another Jaxb Gradle plugin. 

Any suggestions?

**Comment by m-raab** [comment]
Release 6 created with Gradle 8 support

**Comment by timakden** [comment]
> I think this repo is not maintained anymore. Time to switch to another Jaxb Gradle plugin.
> 
> Any suggestions?

It seems that the only updating plugin is https://plugins.gradle.org/plugin/com.github.seanrl.jaxb
