### ISSUE TITLE
schema gen fails 

### ISSUE THREAD

**Issue by shavo007** [IntershopCommunicationsAG/jaxb-gradle-plugin#8]
Hi,

I have a schema gen task that fails. 

Exception is:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jaxbSchemaGenOnDemand'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)


```

This is my base class:

```
@XmlRootElement(name = "Archive")
@XmlType(name = "")
@Data
public class Archive {

    @XmlElement(name = "Incident")
    @XmlElementWrapper(name = "Incidents")
    private List<Incident> incidents;
}


```

I believe this maybe an issue as Im using lombok. Funny thing is that my schema generates but i still get an exception when I run the build.

```

  id 'com.intershop.gradle.jaxb' version '2.0.0'

jaxb {
    schemaGen {

        onDemand {
            javaFiles = fileTree(dir: 'src/main/java', include: 'com/redflex/alcyon/raidr/domain/Archive.java')
            namespaceconfigs = ['': 'ondemand.xsd']
            outputDir = file("src/main/resources/static")
        }

}

```

**Comment by m-raab** [comment]
I see, that you generate the schema to the source directory. That's not ok. Please use the output of the schema gen task for additional input of the resource task.

**Comment by shavo007** [comment]
with spring boot to expose a static asset it needs to reside under that location.

**Comment by m-raab** [comment]
add an example to test

**Comment by m-raab** [comment]
I think the file must be part of the resources. In this case it is necessary to extend the directory list of resource in the main source set
